steps:
  # Build the container image
  - name: 'docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/devops-registry/devopsapp:$COMMIT_SHA',
      '.' 
    ]

# This tells Cloud Build to push the image to the specified location
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/devops-registry/devopsapp:$COMMIT_SHA'

# Specify logging options to resolve the service account bucket error
options:
  logging: CLOUD_LOGGING_ONLY
